### ISSUE TITLE
Unable to connect Team Foundation Server from IntelliJ Ultimate

### ISSUE THREAD

**Issue by subodhpathak** [Microsoft/azure-devops-intellij#105]
After providing Server URL, I am unable to login to Team Foundation Server. My credential works fine using IntelliJ Integration Plugin. 

Not sure about difference between TFS and TFVC, why these two terminology? Any specific service needs to be switched on TFS server. We have TFS 2015 in premise. Do I need to disable IntelliJ's TFSIntegration plugin?

**Comment by atarikguney** [comment]
This issue happens to me with Jetbrains Rider (the new .NET IDE). We have recently moved to TFS 2017 and I cannot authenticate against it using TFVC. The same crendetials work in VS2017 and Web portal of TFS 2017. I keep getting the following exception:

![image](https://user-images.githubusercontent.com/369188/31905846-ab637980-b7ec-11e7-941b-c8376be388ba.png)

**Comment by JoelDewey** [comment]
I had a similar issue with my organization's on-premise TFS. I noticed that I had a SSLHandshakeException/ValidatorException appear in my Rider logs right after my TFS authentication attempts. The error complained that the PKIX path failed to build.

Some digging revealed an [Upsource help document describing the exact same issue](https://upsource-support.jetbrains.com/hc/en-us/articles/206545609-Using-a-self-signed-certificate-to-connect-to-a-VCS-server). In the article, it describes adding the certificate to the JVM's key store:

`keytool -import -alias my-vcs-server-host -keystore <Upsource_dir>internal/java/linux-x64/jre/lib/security/cacerts -file path-to-certificate-file`

I exported the certificate for the TFS server using Firefox and imported it into Rider's JVM using the above `keytool` command. When `keytool` asked if I wanted to trust the certificate, I answered `yes`. This fixed the issue for me and now I am able to log into my organization's TFS from Rider.

Some other (hopefully) helpful notes:

- I am using the JVM that is bundled with Rider.
- On my Windows 10 machine, keytool is located at: `C:\Program Files\JetBrains\JetBrains Rider 2018.1\jre64\bin`
- I found the `cacerts` key store at: `C:\Program Files\JetBrains\JetBrains Rider 2018.1\jre64\lib\security\cacerts`
- I set the alias to the Common Name (CN) of the server the certificate was _issued to_ as shown by Firefox and in my case it worked; your mileage may vary.
- The certificate is not self-signed.
- In my case, `keytool` had to be executed with administrator privileges (via an elevated Command Prompt).
- I saved my exported certificate with a .pem extension.
- I had Rider closed when I ran the `keytool` command and only opened it after the import had finished.
- The default password for the key store is `changeit`.

I hope this helps someone!

**Comment by ForNeVeR** [comment]
Hello! From next release, you'll be able to control the certificates through IDEA (or other IDE) certificate manager (Settings | Tools | Server Certificates). In-process TFS client will respect the certificates set up through UI, so you won't need to do anything about `cacerts` inside of the JetBrains-provided Java runtime.

Standalone client (aka `tf.cmd`) will still require external setup through the usual means (`keytool`) though, because IDEA-based IDEs have no control of the certificate settings of an external JDK.

**Comment by jimmycallaghan** [comment]
This very detailed solution solved my problem. Although I had added the certificate to Rider, it was NOT being used by tf.exe. I changed the tf.cmd file to ensure that it was using my chosen installation of Java. Then I added the certificate to the cacerts of that Java installation. Worked immediately. I was struggling with this problem for 3 hours before reading this. THANKS!

**Comment by Skince** [comment]
@jimmycallaghan Could you please elaborate on how you changed the tf.cmd? Would be much appreciated.

**Comment by eldamir** [comment]
It is 2022, I'm running Rider version 2022.1, and I'm having this problem. Connecting to office network through VPN, in case that may matter.

- Added certs to Rider's internal store
- Imported certs via keytool to cacerts for the jre that tf.cmd uses
- Restarted rider

Still not working.

@JoelDewey have you had further issues with this these later years and found a solution, or how have you been getting on?

**Comment by JoelDewey** [comment]
> It is 2022, I'm running Rider version 2022.1, and I'm having this problem. Connecting to office network through VPN, in case that may matter.
> 
>     * Added certs to Rider's internal store
> 
>     * Imported certs via keytool to cacerts for the jre that tf.cmd uses
> 
>     * Restarted rider
> 
> 
> Still not working.
> 
> @JoelDewey have you had further issues with this these later years and found a solution, or how have you been getting on?

Hey @eldamir. My company has moved away from TFS and so I've not had to maintain the workaround on my machine. I'm afraid I don't have any updated steps.

Best of luck to you.

**Comment by eldamir** [comment]
Alright @JoelDewey, thanks anyway... Colleagues are telling me to go buy VS instead, but I really don't want to. It is pretty expensive, and I rely on Jetbrains tools already for everything else, so really don't want to switch 😟
