### ISSUE TITLE
Can not update or uninstall Visual Studio Team Services plugin

### ISSUE THREAD

**Issue by julia-vaseva** [microsoft/azure-devops-intellij#109]
Rider user: "When I open Rider, there is a message that tells me that I could update the plugin "Visual Studio Team Services" from Version 1.122.0 to 1.123.0. When I click on update, Rider does something and then wants to restart. After I restart Rider, the message is still there and wants me to update from 1.122.0 to 1.123.0. 
Since I don't need any connection to VS Team Services, I wanted to remove the plugin at all. But the little "uninstall" button in the Plugins window ist just grey, without telling me why. "

https://youtrack.jetbrains.com/issue/RIDER-9783

**Comment by JohnStov** [comment]
I also see this exact issue. Also, I can't configure the plugin.  I try to point it at tf.exe, but all I get is a message saying "The specified path does not lead to a valid TF executable"

**Comment by julia-vaseva** [comment]
@leantk Could you please comment on this? Lots of Rider users suffer from this issue.

**Comment by kaylangan** [comment]
@JohnStov can you try pointing it to tf.cmd?

**Comment by ForNeVeR** [comment]
I believe we have fixed the issue on IntelliJ side since then. And, yes, the plugin only supports `tf.cmd` (you'll get the link to download the client in the modern plugin versions), this is by design. Closing as answered.
