### ISSUE TITLE
Change detection issue in TFVC plugin for webstorm

### ISSUE THREAD

**Issue by abhay-infrrd** [microsoft/azure-devops-intellij#122]
The issue is there is a folder in node_modules > ajv which has files which start with '$' such as '$data.js' or '$data.json' which causes the plugin to crash with error asking the user to remove '$' and try indexing again.
I have added node modules in the ignore list but still it keeps failing for that same reason.
Is there a workaround for this.
I have issues in updating the project as well as checking in if these kind of files are present but ideally the plugin should not scan the node modules folder even if I add anything in the future also.

**Comment by EricTheRed-VT** [comment]
I'm having this issue as well, I've deleted everything in my node_modules folder and it's still crashing.

**Comment by ForNeVeR** [comment]
I believe we have fixed it with #217. Thanks for reporting and sorry for the pause!
