### ISSUE TITLE
the specified path does not lead to a valid tf executable

### ISSUE THREAD

**Issue by gaurangpatel6688** [microsoft/azure-devops-intellij#127]
I am getting this "the specified path does not lead to a valid tf executable" error when I am trying to set path for TFVC. The given path has the tf.exe file but still I am getting the error
[idea.log](https://github.com/Microsoft/vso-intellij/files/1555565/idea.log)

**Comment by SrivatsaMarichi** [comment]
@gaurangpatel6688 refer [here](https://github.com/Microsoft/vso-intellij/issues/136) for the solution which I faced too.

**Comment by ForNeVeR** [comment]
Unfortunately, we don't support the `tf.exe` (you're referring to the one from Visual Studio, I presume). Only `tf.cmd` from the https://github.com/Microsoft/team-explorer-everywhere is supported.
