### ISSUE TITLE
Performing VCS Refresh too slow before checkin

### ISSUE THREAD

**Issue by davidinhong** [microsoft/azure-devops-intellij#130]
Sometimes when I try to check-in some file appears the "Performing VCS refresh" window and it remains for a very long time...
Some help please?

[idea.log](https://github.com/Microsoft/vso-intellij/files/1639301/idea.log)

**Comment by SrivatsaMarichi** [comment]
I too have the same issue. It doesn't allow me to checkin. PFA logs for the same.

[as_error.txt](https://github.com/Microsoft/vso-intellij/files/1918220/as_error.txt)

**Comment by SteveSartain** [comment]
I have the same issue. I think it's because you can only create LOCAL workspaces and not SERVER ones. For large solutions, even in Visual Studio, it is recommended to use server workspaces.  This is a feature that is actually preventing us from adopting Rider

**Comment by dillius** [comment]
This is a massive problem.

I have gone through the troubleshooting steps of ensuring there aren't very many unversioned files (have 18) but honestly this plugin is almost completely unusable with a decently sized project.

I find myself actually working in Rider (which crashes far less than VS) and having to switch to VS for commits and merges (merges still take forever but at least the refreshes don't). 

The surprising thing to me is that I have VS use the same workspace as my Rider for these commits, which is a Local, but it is still faster at the refresh.

**Comment by fdimauro** [comment]
Yes the wait time is ridiculous. I am reverting back to the command line to do my commits. What the heck is Intellij doing for so long?

**Comment by ForNeVeR** [comment]
Hey, the checkin performance was greatly improved by these PRs: #181, #185. I would consider this as fixed for now, but please feel free to drop a comment if the latest plugin version still shows bad checkin performance in your use case.

**Comment by KyleStay** [comment]
I'm not having pretty unacceptable performance. Probably because there are a lot of files that need to be set to ignore, but it would be nice if the plugin had a better way of handling this.

**Comment by ForNeVeR** [comment]
@KyleStay, thanks for feedback!

Could you please elaborate more? Have you tried enabling the "Use reactive client" checkbox in the plugin TFVC settings? Also, could you tell me how many files are there in your repository, how many are shown on the "Local changes" tab, and how many of them are ignored?

**Comment by kenguest** [comment]
having this problem at the moment - but deleted/renamed the vc-log directory and that has seemed to have fixed the issue
