### ISSUE TITLE
Link to TF Command line tool not working

### ISSUE THREAD

**Issue by haakoo** [microsoft/azure-devops-intellij#136]
I posted this over at [Riders bug tracking](https://youtrack.jetbrains.com/issue/RIDER-14939) first, but they sent me here.

When trying out Rider a few days ago, I needed to checkout a project from TFS using TFVC. This gave me a helpful popup that told me I needed to install the TF command line tool (se attached image). The message includes a link to https://docs.microsoft.com/en-us/vsts/java/Docs/tools/intelliJ#_tfvc-support that returns a 404.

![jetbrains rider tfvc link error](https://user-images.githubusercontent.com/1096499/38482602-53598f14-3bd0-11e8-8d65-f08b202198e8.png)

**Comment by SrivatsaMarichi** [comment]
I am facing the same issue in android studio 3.1.1 while connecting to TFS 2018 U1.

**Comment by mfilippov** [comment]
@jeschu1 Fixed in #136

**Comment by ForNeVeR** [comment]
Closing as fixed.
