### ISSUE TITLE
Unable to connect to TFS 2018 Update 2 from Android Studio

### ISSUE THREAD

**Issue by SrivatsaMarichi** [Microsoft/azure-devops-intellij#175]
I am trying to connect to TFS 2018 Update 2 from Android Studio and I am facing the below error.

**Unable to authenticate to Team Foundation Server 'http://TFS_URL'. Verify access to the server URL and try Connect again**

PFA log for the same.

[idea.log](https://github.com/Microsoft/azure-devops-intellij/files/2400112/idea.log)

**Plugin Version**
1.150.0 and was downloaded from [here](http://plugins.jetbrains.com/plugin/7981-visual-studio-team-services)

**Android Studio**
3.1.4

**Comment by SrivatsaMarichi** [comment]
Guys, any updates here?

**Comment by Spidermain50** [comment]
I am having the same issue as well.

**Comment by Spidermain50** [comment]
@SrivatsaMarichi It ended up being a network issue in my case. Our firewall settings were too strict on Android Studio causing it not to be able to connect to our on premise TFS. I hope that helps you.
