### ISSUE TITLE
Take too long to start calculating the commits and changes for Android studio 3.2.1

### ISSUE THREAD

**Issue by CodeFactory2011** [microsoft/azure-devops-intellij#181]
Android studio version 3.2.1
After i picked a target branch to create a pull request, it took over 5 minutes to start calculating the changes and commits.

**Comment by caveman-dick** [comment]
I regularly get this in Rider. Never knew the functionality existed until it randomly started working in a few seconds. Now back to it taking so long that I have to manually fill out the details.

**Comment by ForNeVeR** [comment]
@caveman-dick could you please try the same in Rider 2019.1 EAP 7? It already includes a newer version of Azure Devops plugin, and the process of calculating the change set for commit should be significantly faster (see https://github.com/Microsoft/azure-devops-intellij/pull/185 for metrics).

**Comment by caveman-dick** [comment]
@ForNeVeR Already using EAP7:

![image](https://user-images.githubusercontent.com/516600/56726725-3f121780-6747-11e9-8002-7810d135f340.png)

Just timed it and it took just over 8 mins to populate the first time and then for the one extra commit with only 4 lines changed it took about 17 mins (I actually timed it!).

Until that it looks like:

![image](https://user-images.githubusercontent.com/516600/56732466-5b1cb580-6755-11e9-810c-94bdbe3269b8.png)

I will try and get video proof.

**Comment by ForNeVeR** [comment]
@caveman-dick could you please share your IDE logs? 
1. Reproduce the issue
2. **Help | Compress Logs and Show in Explorer** in the main menu
3. Then send the resulting archive to ivan.migalev@jetbrains.com _(please do not share the logs publicly, as they could contain private data)_
