### ISSUE TITLE
Updating plugin freezes Webstorm on project open

### ISSUE THREAD

**Issue by EricTheRed-VT** [microsoft/azure-devops-intellij#210]
After updating the plugin from v1.150.0 to v151.2 or v1.152.0, Webstorm completely freezes up when I open a project that has version control. (Note: we use on-prem TFS with TFVC, not Git.)

This UI freeze fix https://github.com/microsoft/azure-devops-intellij/commit/fb8972226414a0fe7d8863f609462eff688aacff seems to be Git-specific, perhaps there is a similar error with TFS/TFVC-specific code?

specs for reference:
Webstorm 2019.1.3 (Build #WS-191.7479.14)
Windows 10 Pro (version 10.0.17763)
Microsoft Visual Studio Team Foundation Server (Version 15.117.27024.0)

**Comment by ForNeVeR** [comment]
@EricTheRed-VT hello, could you please compress the WebStorm logs (**Help | Compress Logs and Show in Explorer**) and send them to ivan.migalev@jetbrains.com?

The logs should contain the freeze thread dumps (usually produced by the IDE automatically when the freeze is detected), and they will help us to find the reason and fix it.

**Comment by ForNeVeR** [comment]
@EricTheRed-VT from your logs I was able to determine that the TFS client fails due to `--add-module` option being passed to it.

May it be that you have `TF_ADDITIONAL_JAVA_ARGS` environment variable defined that contains the `--add-module`, while you're running the TFS client on an "older" (i.e. Java 8) JVM?

`--add-module` is a fix to run the TFS client on Java 11, but it's not applicable to Java 9.

**Comment by EricTheRed-VT** [comment]
@ForNeVeR It seems that with v1.150.0, TEE-CLC was run on my local Java install, and with v151.2 or v1.152.0 TEE-CLC was run with Webstorm's built-in SDK.

I used the JB SDK Bintray Downloader plugin to make Webstorm use JRE 9.x instead of 8.x, which solved the issue.

Thanks for the help!

**Comment by ForNeVeR** [comment]
@EricTheRed-VT thanks for confirming.

About other issues you encounter: we're thinking about using the embedded JDK always (#126) and providing the `--add-module` fix based on the embedded JDK version after that.
