### ISSUE TITLE
login is not working. continuously prompting for credentials and failing. 

### ISSUE THREAD

**Issue by SrinivasM13** [microsoft/azure-devops-intellij#233]
After recent update Azure Devops TFS login failing and not able to use app. 
**steps to reproduce.**
1. click on Pull requests tab/Work items and credentials prompt will come
2. Enter credentials and click OK, which will prompt for credentials 2nd time
3. Enter credentials 2nd time as well but still login fails. Error attached. 
![image](https://user-images.githubusercontent.com/26898666/62004355-9b147f80-b12c-11e9-8b0a-c5963ba53118.png)

![image](https://user-images.githubusercontent.com/26898666/62004372-ceefa500-b12c-11e9-9185-faaf2d55dddf.png)

**Comment by ForNeVeR** [comment]
This window looks unusual. Are you using on-premise installation of TFS/Azure DevOps Server? Could you please share the IDE logs? **Help → Compress Logs and Show in Explorer**, and then send them to ivan.migalev@jetbrains.com

**Comment by SrinivasM13** [comment]
Im using intellij community edition.  I will try to check logs and share. 
![image](https://user-images.githubusercontent.com/26898666/62004414-7d93e580-b12d-11e9-8f37-3425eb120bc4.png)

and below plugin
![image](https://user-images.githubusercontent.com/26898666/62004430-b6cc5580-b12d-11e9-8014-8e758f8a44b1.png)

**Comment by ForNeVeR** [comment]
I was asking about the server you use. Is it dev.azure.com or <something>.visualstudio.com or some other server instance?

**Comment by SrinivasM13** [comment]
Server details below. Please let me know in case any other details required. 
About Microsoft Visual Studio Team Foundation Server
Microsoft Visual Studio Team Foundation Server
Version 14.102.25423.0

URL is something internal. http://tfs.something.com/tfs/project/_git/website

**Comment by ForNeVeR** [comment]
For now, possible workaround for you would be to roll back to previous plugin version. And please. if possible, share the IDE logs with the address I mentioned earlier.

**Comment by SrinivasM13** [comment]
could you please help me with steps to roll back to previous plugin version.
FYI. i have downloaded zip file of previous version and tried selecting to install from disk. but getting below error.
![image](https://user-images.githubusercontent.com/26898666/62004774-fc8b1d00-b131-11e9-9311-8440ba9a9107.png)

**Comment by ForNeVeR** [comment]
Where did you got this file?

**Comment by SrinivasM13** [comment]
thanks for link. i realized im trying with github source zip.

**Comment by SrinivasM13** [comment]
Issue from recent update this app is not considering proxy exceptions under settings under IDEA and always trying to connect with proxy for internal link and failing. updated proxy settings to auto detect and now working fine.

**Comment by ForNeVeR** [comment]
Thanks for reporting, we'll keep this issue in mind.
