### ISSUE TITLE
can't disable multiple check-out 

### ISSUE THREAD

**Issue by hosamyousof** [microsoft/azure-devops-intellij#272]
We're working with azure DevOps TFVC and android studio IDE
We want to disable multiple checkouts for the files so only one developer can work on the file. 

We were able to do it in the Visual Studio .Net Projects easily but we couldn't in android studio using azure devops plugin.

How cant we achieve this in android studio with azure devops TFVC ?

I tried to lock a file but I got error says "... **Checkout locks are not supported in local workspaces**"
I tried to change the workspace location from local to server but It's disabled !!

![image](https://user-images.githubusercontent.com/16549201/70526707-40b81080-1b5b-11ea-9ad0-c1f0e83ebcdd.png)

**Error:TF400022: The item $/Test App Project/app/src/main/java/com/example/testapp1/ui/dashboard/DashboardFragment.java cannot be locked for checkout in workspace WINDOWS-1VTOOGG_TestAppProject;Hosam. Checkout locks are not supported in local workspaces.**

![image](https://user-images.githubusercontent.com/16549201/70526830-7eb53480-1b5b-11ea-91cf-4662e8ea84b3.png)

![image](https://user-images.githubusercontent.com/16549201/70527250-81fcf000-1b5c-11ea-9d81-f17475eeab4b.png)

**Comment by ForNeVeR** [comment]
Unfortunately, this is true. This plugin doesn't currently support the server workspaces, and, thus, it cannot support the check out locks. At the current moment, there're no plans  I'm aware of to add the server workspaces.

**Comment by ForNeVeR** [comment]
Hello. In scope of #325, we're going to support checkout of new server workspaces (there'll be a checkbox in the checkout dialog). Closing the issue as subset of #325.
