### ISSUE TITLE
Plugin is available for Rider and unusable

### ISSUE THREAD

**Issue by SayusiAndo** [microsoft/azure-devops-intellij#277]
Hi All,

I found this plugin in Rider - Preferences - Plugins - Marketplace, and I installed it, but can't do anything with it. I can't even set it up. Please, find the attached screenshot below.

Any plans to make this plugin usable in Rider?

<img width="1445" alt="Screenshot 2019-12-16 at 21 46 47" src="https://user-images.githubusercontent.com/5106373/70941839-a28de400-204d-11ea-83fa-c6c5138bfbaa.png">

**Comment by ForNeVeR** [comment]
Hello. I'd insist (😏) that the plugin is usable in Rider, we're actively testing it in both IDEA and Rider.

It may be unclear how to set it up properly, I'm ready to answer your questions.

Usual workflow is to either clone the repository via plugin (**VCS** → **Get From Version Control** → Choose **Azure DevOps Git** / **Azure DevOps TFVC**) or to enable the version control in an existing repository (I think that's **VCS** → **Enable Version Control**).

Please state your issues more clearly: which plugin features you're interested in?

**Comment by ForNeVeR** [comment]
Closed due to user inactivity. If you have any questions, feel free to reopen/comment/open a new issue.
