### ISSUE TITLE
Automatically enable VCS when an appropriate project is opened

### ISSUE THREAD

**Issue by ForNeVeR** [microsoft/azure-devops-intellij#284]
Consider I've performed the following operations in my terminal:

```console
$ tf workspace /new /collection:https://username.visualstudio.com/ testworkspace
$ tf workfold /map /workspace:testworkspace $/project/directory ./directory
$ tf get ./directory /recursive
$ idea ./directory
```

After that, TFVC should automatically be enabled in the opened IDE. Currently, users have to enable it manually via the **VCS → Enable Version Control…** main menu item.

**Comment by fdcds** [comment]
I have a repository checked out from Azure DevOps (remote: `git@ssh.dev.azure.com:v3/...`), but IntelliJ's Version Control (tab at bottom of screen) > Pull Requests shows "This project is not associated with Team Foundation Git. To use pull requests, import this project into Team Foundation Git."

See-Also: https://developercommunity.visualstudio.com/idea/383712/migrate-from-regular-git-to-team-services-git-in-i.html
