### ISSUE TITLE
Incorrect Azure Devops pull request link

### ISSUE THREAD

**Issue by pecanw** [microsoft/azure-devops-intellij#297]
After creating a pull request a message is displayed with a link to the pull request UI on Azure Devops. However the link contains `#view=discussion` at the end which (I guess) prevents displaying the page correctly...

**Comment by ForNeVeR** [comment]
Hello and thanks for your report! I believe we have already fixed that in https://github.com/microsoft/azure-devops-intellij/pull/283 (but haven't released this fix yet).

I'll check if that's the case.

**Comment by ForNeVeR** [comment]
This issue, indeed, were fixed by #283. But `#discussion` is unnecessary after the link, so I'll merge your pull request, too.

Thanks for your work! We're preparing a new plugin version to be released soon.
