### ISSUE TITLE
Problem with diacritical characters in Rider 

### ISSUE THREAD

**Issue by Boudyno** [microsoft/azure-devops-intellij#311]
Hello

In JetBrain's Rider if I display Repository tool window and want to see changesets history, the characters with czech diacritics }but I suppose is is more general issue] are crippled:
![image](https://user-images.githubusercontent.com/14122510/76966615-8ccadc00-6926-11ea-9401-99c8c4c43a34.png)

If I show history using tf.exe, it is OK:
![image](https://user-images.githubusercontent.com/14122510/76966738-b5eb6c80-6926-11ea-922c-d1b4e30599a1.png)

Thanks for fix or advice if it can be fixed with some settings.
Bouda

**Comment by ForNeVeR** [comment]
Hello! Unfortunately, this is a known encoding issue, and we weren't able to fix it yet.

[A similar issue](https://youtrack.jetbrains.com/issue/RIDER-30366) has been reported to the Rider issue tracker, feel free to vote for it.

**Comment by ForNeVeR** [comment]
When fixing this, please also check CJK characters (see #387 for details).
