### ISSUE TITLE
Error connecting to existing server Workspace

### ISSUE THREAD

**Issue by streamstr** [microsoft/azure-devops-intellij#324]
Every time I open any solution in Rider, and then try to get latest version, this error occurs:

`com.microsoft.alm.plugin.external.exceptions.ToolAuthenticationException: KEY_TF_AUTH_FAIL
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.throwIfError(FindWorkspaceCommand.java:133)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:91)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:26)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)`

Workspace I'm working in was created in Visual Studio.
I tried to update credentials here:
![image](https://user-images.githubusercontent.com/9412086/78419409-2647fc80-764e-11ea-9391-d498061fa8c5.png)
but nothing has changed.

**Comment by ForNeVeR** [comment]
Hello. Could it be that the Visual Studio workspace is a Server one? Could you pleae check the workspace settings? Unfortunately, we don't support the server workspaces (yet), and this is one of the errors that could happen on a Server workspace.

**Comment by streamstr** [comment]
@ForNeVeR yes, this workspace is server. When support for server workspaces can be expected?

**Comment by ForNeVeR** [comment]
We're looking into it, see #325 for the current progress.

**Comment by ForNeVeR** [comment]
After spending some time on #325, I'm sure this issue is a proper subset of #325, so I'll close it.

**Comment by DdarkSideE** [comment]
Hello,
I have the same problem, but the workspace is local
If I go to VCS->TFVC->Manager workspaces I can see the old workspaces that have already been deleted. So I press "reload workplaces" and get "An error occurred: Access denied connecting to TFS server". I updated the credentials using Rider settings.
Can it be something with certificate? I have exported company root cert using Rider Settings->Tools->Server Certificates, but it has changed nothing.

**Comment by ForNeVeR** [comment]
@DdarkSideE,
> I have the same problem, but the workspace is local

Then this is another issue. Please check you're using the latest version of the plugin, and then open a new ticket, and attach IDE logs. Also, some details on your TFVC server would help.
