### ISSUE TITLE
Server workspace support

### ISSUE THREAD

**Issue by ForNeVeR** [microsoft/azure-devops-intellij#325]
This is an umbrella issue for server workspace support in Azure DevOps plugin.

Points to consider:
- [x] #91: checking out a repository into a server workspace
- [x] #324: importing of existing server workspace
- [x] working around the read only FS flags in the server workspace
- [x] check whether both classic and reactive clients support main operations on a server workspace
- [x] other issues:
  - [x] #272

For now, the main and first obstacle users encounter when they try to open a server workspace is [this code](https://github.com/microsoft/azure-devops-intellij/blob/5fb7e82c363b2172c0ac62d2e6df338ffefb82d2/plugin/src/com/microsoft/alm/plugin/external/commands/FindWorkspaceCommand.java#L65-L66): we never pass the authentication data over to the client (even if we know it's required), so nothing actually works.

**Comment by stickian** [comment]
Now that JetBrains has dropped support for their TFS plugin, their products do not support server workspaces. Are there any plans in the near future for this plugin to support server workspaces?

**Comment by maui1911** [comment]
Can I follow this issue to know when server workspaces is done?
