### ISSUE TITLE
Adding files is slow

### ISSUE THREAD

**Issue by julianess** [microsoft/azure-devops-intellij#338]
When trying to add files in WebStorm 2020.1 in a local workspace this causes the IDE to freeze and show up a dialog "Schedule Addition" for about 40-60 seconds. This is way too long for such a fundamental action while wokring with a VCS.
![2020-04-23 17_01_24-Window](https://user-images.githubusercontent.com/9079614/80115011-87475e00-8584-11ea-9f99-6396839a41f8.png)

The file is created after 1-2 sec and visible in the project-tree but the dialog is still present.

My System:
- Windows 10
- Latest WebStorm (2020.1)
- Azure DevOps Plugin 1.159.0
- Local TFS Workspace (~130,000 Files)

I know local workspaces are advised to be a maximum of ~100,000 files but as the plugin currently doesn't support server-workspaces I had to change to local instead.

**Comment by ForNeVeR** [comment]
Hello. Yes, we're aware of many performance problems, but they're being actively fixed in the reactive client (which is still in experimental state). Could you please check your settings: have you tried enabling the reactive TFVC client? It is designed exactly for the described case.

**Comment by julianess** [comment]
Yes the experimental reactive client is already enabled.
Both a classic client (tf.cmd) and a Visual Studio TF Client are installed, too.
I've found similar (the same) issues with the AzureDevOps Plugin in Rider (https://youtrack.jetbrains.com/issue/RIDER-36869) and that this part should be implemented in the reactive client to be fast enough. But as of now it isn't part of the reactive client, isn't it?

**Comment by ForNeVeR** [comment]
Ah, I'm sorry, you're right. I forget we didn't implemented that part.

We will implement it, then.

**Comment by julianess** [comment]
That sounds good. How about the priority of this enhancement? As of WebStorm 2020.1 this plugin is more important than ever because the old TFS plugin isn't supported anymore and this seems to be the only plugin working fine with TFS for most frequent use-cases. 
So current 'solutions' are to stay on 2019.3 or wait 60 sec to add a file. Both not very nice as I think.

**Comment by ForNeVeR** [comment]
Don't worry, I undertand the situation. This enhancement is one of the top-prioritised ones (and, notably, shouldn't be too hard to implement).

**Comment by streamstr** [comment]
I'm experiencing very slow files and folders addition too. It is very annoying. I guess when this is fixed a new version of plugin will be released? Approximately, when we can expect this to happen?
