### ISSUE TITLE
Unable to perform the get operation because it is writable

### ISSUE THREAD

**Issue by mdindoffer** [microsoft/azure-devops-intellij#348]
Trying to pull changes from the server I get the following warning:
`Warning:Warning entrypoint.sh - Unable to perform the get operation because it is writable`
The file in question did not exist on my local computer, rather was created in a changeset I just pulled in.
The file was indeed downloaded, however with some strange contents - it has slightly different content than what is shown in TFSHub. Idea shows a warning when opening the file:
`Outdated version. Modified by X Today 10:06` and shows the diff.
Updating the file now fails and the changeset remains only partially pulled in, as shown in the screenshot:
![Screenshot from 2020-05-07 16-58-18](https://user-images.githubusercontent.com/12681399/81310649-a8c83f80-9084-11ea-858b-d6983827263c.png)

I have absolutely no idea how something like this could happen. However, I've googled up the issue and people usually resolved it via a `clean` or `/overwrite` flag. Is this something the plugin is able to do?

**Comment by ForNeVeR** [comment]
Can you try to delete the file completely, and then roll back the operation using the IDE? If not, then probably plugin isn't able to recover from this problem, and you'll have to perform the operation manually in the terminal. Try the following command from the root of the repository:

```console
$ tf get /overwrite $/<…>/src/main/docker/bin/entrypoint.sh
```

**Comment by mdindoffer** [comment]
Thanks for the suggestion. I deleted the file and then pulled in the changes from the server.
It successfully downloaded the correct version of the file, so the issue at hand is solved.

Just FYI, I was unable to unable to fix it via rollback, because the plugin did not detect any changes after I deleted the file. Even when trying to refresh the `Local Changes` multiple times. This is something that's happening a lot, but so far I couldn't find any guaranteed reproducible steps.

**Comment by ForNeVeR** [comment]
> Just FYI, I was unable to unable to fix it via rollback, because the plugin did not detect any changes after I deleted the file.

Ah, yes, I'm sorry, this is known issue: for some reason, currently we're unable to detect items that were detected without corresponding TFVC actions. It is on our radar.
