### ISSUE TITLE
Multiple TEE-CLC processes with high memory usage are spawned by Rider

### ISSUE THREAD

**Issue by streamstr** [microsoft/azure-devops-intellij#356]
There are **four (!) processes** which host TEE-CLC instances:
![image](https://user-images.githubusercontent.com/9412086/82141797-e37a6680-9840-11ea-9b6d-a6afe52c8678.png)

Each process uses about 630 MB of memory. 630 x 4 = 2520 MB (**2.5 GB**)
This seems as unnecessary waste of computer resources and bug: why several processes are needed? Why there cannot be single process? 

Details for one of processes:
![image](https://user-images.githubusercontent.com/9412086/82142001-efb2f380-9841-11ea-9e9b-6b66cd69933e.png)
![image](https://user-images.githubusercontent.com/9412086/82142039-3c96ca00-9842-11ea-90bb-9e3c652475cf.png)

**Comment by ForNeVeR** [comment]
Yeah, I've noticed this, too, and I think it will be fixed by #354. Some of the workspace runners were incorrectly introducing their own cache entries (that were never reused).
