### ISSUE TITLE
Fatal Exception thrown on Scheduler.Worker thread

### ISSUE THREAD

**Issue by libin049** [microsoft/azure-devops-intellij#362]
![image](https://user-images.githubusercontent.com/7247717/85116631-34221c80-b250-11ea-9fe9-4d3dba5575f4.png)

**Comment by ForNeVeR** [comment]
Hello! Please report this issue to the [Azure Toolkit for IntelliJ](https://github.com/microsoft/azure-tools-for-java) plugin repository. This is another plugin (with a similar name though).
