### ISSUE TITLE
TFVC actions are not appearing on PyCharm Toolbar menu

### ISSUE THREAD

**Issue by dilnag** [microsoft/azure-devops-intellij#407]
Details of the Project: 
Its a Robotic frame work project , using Selenium and Python. 
Python 3.7.4
PyCharm CE2019.1
Azure DevOps plugin installed in PyCharm
java version "1.8.0_121"
OS Name:                   Microsoft Windows Server 2016 Standard
OS Version:                10.0.14393 N/A Build 14393

In PyCharm, version control is enabled and TFVC is selected as version control system.
I was able to check out the latest code from the server by following the below path
    Then go to VCS--> Check out from Version Control--> Azure DevOps TFVS
Issue: I am trying to commit my changes to our TFS server. But TFVS options are not appearing in my PyCharm toolbar menu. 
I have tried the below options:

Commit File option added to Menus and Toolbar section through PyCharm settings.
![image](https://user-images.githubusercontent.com/74247860/98678172-0dc36180-2356-11eb-8f71-4818ed4cbb2a.png)
![image](https://user-images.githubusercontent.com/74247860/98678192-187df680-2356-11eb-9d10-f63592503efb.png)

But that commit File option is not appearing in my PyCharm toolbar even after restarting the IDE.

![image](https://user-images.githubusercontent.com/74247860/98678493-904c2100-2356-11eb-8747-bfeea95c5cc1.png)

Thanks in advance

**Comment by ForNeVeR** [comment]
I'm not sure about toolbar actions right now. Could you see the VCS tool window?

**Comment by dilnag** [comment]
Yes, VCS option is able to see like below.
![image](https://user-images.githubusercontent.com/74247860/98800402-3efc6a00-2408-11eb-9558-5ab053a8a461.png)

**Comment by ForNeVeR** [comment]
I'm sorry, not the VCS menu; the VCS tool window, like this one:
![image](https://user-images.githubusercontent.com/92793/98802187-7b9a8680-2445-11eb-992f-2c5f00cde40b.png)

Though I think that it's not available because the VCS menu doesn't show the actions like **Commit**, too.

Could you please show a screenshot of Settings → Version Control page?

**Comment by dilnag** [comment]
PFB:
![image](https://user-images.githubusercontent.com/74247860/98805963-55a6bf00-2410-11eb-9405-58758396514b.png)
![image](https://user-images.githubusercontent.com/74247860/98806063-84bd3080-2410-11eb-9413-d00d1dec4179.png)
![image](https://user-images.githubusercontent.com/74247860/98806141-a28a9580-2410-11eb-99e1-ba2d72fe4975.png)

**Comment by ForNeVeR** [comment]
From this I assume that TFVC wasn't enabled, or something is broken.
![image](https://user-images.githubusercontent.com/92793/98916680-06d75300-24fe-11eb-9a96-56e728126622.png)

Could you try to remove this source root and enable it again?

**Comment by dilnag** [comment]
Yes, TFVC was not selected there. Now I am able to see that TFVC options in my toolbar. 
Thank you for all your support.

**Comment by ForNeVeR** [comment]
Thanks for your answer.
