### ISSUE TITLE
Support for Authentication to Azure DevOps Services via Personal Access Token

### ISSUE THREAD

**Issue by ajmakanaki** [microsoft/azure-devops-intellij#409]
Any chance to add support for personal access token authentication?

**Comment by ajmakanaki** [comment]
Any chance to add support for personal access token authentication to Azure DevOps Git Repos?

**Comment by ForNeVeR** [comment]
Currently, the plugin already generates PAT for itself when you authenticate on Azure: it neither stores your actual login/password, nor the authentication token received from them, and only store the resulting PAT (properly scoped for project you selected only).

There're no current plans to change this authentication scheme; the authentication is already problematic enough even without new features.

**Comment by ajmakanaki** [comment]
Thanks, this can be closed.

I think my original issue was that I could not authenticate because I used wrong proxy settings. Had to set them manually, with help from a colleague.

**Comment by ForNeVeR** [comment]
Thanks for your answer!

**Comment by TheConstructor** [comment]
@ForNeVeR is there a way to directly provide a PAT? We are using NTLM/Kerberos with HW-token and it seems that is not supported by the plugin
