### ISSUE TITLE
Only able to update credentials/delete configuration, not add new

### ISSUE THREAD

**Issue by eforgacs** [microsoft/azure-devops-intellij#426]
It appears that there is only the option to update credentials, and delete configuration, but not add a new one. Would it be possible to add a button to create a new configuration? If not, what is the recommended course of action for creating a new configuration?

![image](https://user-images.githubusercontent.com/23140027/109829366-71c2ac00-7c0b-11eb-9f8b-6d476314059b.png)

**Comment by ForNeVeR** [comment]
Why would you want to add a new configuration?

**Comment by eforgacs** [comment]
I was thinking it might be useful, if all of the configurations were deleted, and you wanted to create a new one, to be able to do so without starting the process from the beginning.

**Comment by ForNeVeR** [comment]
I don't believe it could be beneficial for a user in the current design (since it's impossible to know what repository URL you're supposed to get credentials for).

**Comment by eforgacs** [comment]
Okay, no problem, I just wanted to bring the idea to the forefront in case it hadn't been mentioned yet. If it's not useful in the current design, I'll close out this suggestion. Thanks!
