### ISSUE TITLE
Plugin not compatible with latest version of Rider

### ISSUE THREAD

**Issue by fourofspades** [microsoft/azure-devops-intellij#471]
Plugin error: Plugin 'TFS' (version '212') is not compatible with the current version of the IDE, because it requires build 213 or older but the current build is RD-213.6461.51

**Comment by ForNeVeR** [comment]
Could you please check which plugin are you talking about? This plugin is not called "TFS" (neither in the plugin name nor in its id). It is "Azure DevOps" or "com.microsoft.vso.idea", and not "TFS".

I assume you're looking for some other plugin.
