### ISSUE TITLE
Plugin update version 

### ISSUE THREAD

**Issue by mohammadghari1376** [microsoft/azure-devops-intellij#476]
hi 
When can I get new version for fix my system bug from the Rider plugins section?

my reported bug : #473

**Comment by ForNeVeR** [comment]
@mohammadghari1376, we are still working on an update. If you're eager to check if it helps, please try [this preview release I've just uploaded](https://github.com/microsoft/azure-devops-intellij/releases/tag/v1.162.1-preview).

Please note this is a preview, and so we did no QA at all. I don't even know if it works, so you're on your own if you are installing it.
