### ISSUE TITLE
Question: is this plugin still being supported?

### ISSUE THREAD

**Issue by vesanieminen** [microsoft/azure-devops-intellij#529]
I see that there are a bunch of commits have been made to this IntelliJ plugin but there hasn't been a new release for over a year now: https://plugins.jetbrains.com/plugin/7981-azure-devops

What's the deal? 🙂

**Comment by ForNeVeR** [comment]
Our QA process has shown additional bugs we are still working on, and we have to fix those before releasing a new version.
