### ISSUE TITLE
IntelliJ 2022.3 : Can't clone repository from organization in Azure DevOps

### ISSUE THREAD

**Issue by mrksph** [microsoft/azure-devops-intellij#551]
Hi,

I'm trying to clone a repo from my company in a organization from Azure DevOps. The plugin correctly signs me in and fetches the repo from the org but when trying to clone it it stays loading until an exception is thrown:

The exception is a 400 HTTP Error with the following response:
{
"$id":"1",
"innerException":null,
"message":"FullScopePatPolicyViolation",
"typeName":"Microsoft.VisualStudio.Services.DelegatedAuthorization.SessionTokenCreateException, Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
"typeKey":"SessionTokenCreateException",
"errorCode":0,
"eventId":3000
}

We use a HTTP and HTTPS proxy and it's already configured in IntelliJ settings.

I just want to be able to create Pull Request from my IDE that's all, how can this be so complicated guys?

**Comment by connorjs** [comment]
I recommend closing issues related to `FullScopePatPolicyViolation` in favor of #481 which, at time of writing, has the most up votes. Let's focus the discussion there.

**Comment by mrksph** [comment]
> I recommend closing issues related to `FullScopePatPolicyViolation` in favor of [#481](https://github.com/microsoft/azure-devops-intellij/issues/481) which, at time of writing, has the most up votes. Let's focus the discussion there.

Ok from my side, closing this one.
