### ISSUE TITLE
Is the project dead or not maintained

### ISSUE THREAD

**Issue by edokan** [microsoft/azure-devops-intellij#563]
Hello,

Is the project still being maintained? I don't see activity and even the simplest of issues are not fixed (eg: 534).

If so, thank you for your effort so far, if not, how can I help?

**Comment by ForNeVeR** [comment]
The project is maintained, but mostly only the critical issues (when it gets incompatible with new IntelliJ versions) are fixed right now.

You are welcome to send a PR, all the PRs get reviewed.
