### ISSUE TITLE
When eula not accepted, no visual feedback using Rider

### ISSUE THREAD

**Issue by bartdkmediahuis** [microsoft/azure-devops-intellij#78]
Needed to manually execute ./tf eula -accept in order to get the TFS plugin up and running in Rider.
Can this be documented or be executed during install ?

**Comment by yacaovsnc** [comment]
Thanks for the feedback.  I agree we should have a simpler way to accept the eula, or at least document this.  Will discuss internally about the best approach.

**Comment by ForNeVeR** [comment]
I believe it was fixed in #152. Thanks for reporting!

**Comment by DdarkSideE** [comment]
Hello,
I got only "Couldn't create TFVC repository in xxx: EULA not accepted" in log without any UI feedback.
Rider 2021.3.2
TEE-CLC-14.135.3
Azure DevOps 1.162.0

**Comment by Briahas** [comment]
1. Open "VCS Operations" modal window
2. Select "Enable Version Control Integration..."
3. Select from the appeared dropdown - "TFVC"
4. Click "OK"

Result: after a couple of popups, a notification appeared: 
![image](https://github.com/microsoft/azure-devops-intellij/assets/6129472/651ef078-6692-4b62-996e-f5914a59ec8a)

Do you think this is an issue with your plugin?

---
JetBrains Rider 2023.1.4
Windows 10.0
.NET 7.0.2 (Server GC)
Non-Bundled Plugins:
    lermitage.intellij.extratci (1.26.0)
    com.intellij.resharper.HeapAllocationsViewer (2023.1.0)
    com.settler.rider.specflow (1.16.1)
    com.tobszarny.activetabhighlighter.plugin.id (1.5.1)
    BrowseWordAtCaret (3.0.5)
    com.nasller.CodeGlancePro (1.6.7)
    ru.adelf.idea.dotenv (2023.1)
    com.mroche.JsonHelper (1.2.0)
    thomas.gian.FoldSearch (2023.04.03)
    com.godwin.json.parser (1.4.1)
    negationhighlighter-rider (0.0.12)
    cognitivecomplexity-rider (2023.1.0)
    String Manipulation (9.9.0)
    net.antelle.intellij-xcode-dark-theme (1.2.4)
    com.yemreak.DarkCode-Theme (1.1)
    net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
    Abc.MoqComplete.Rider (2023.1.0.1)
    com.intellij.resharper.StructuredLogging (2023.1.0.296)
    intellij.prettierJS (231.8770.67)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-231)
    com.microsoft.vso.idea (1.162.2)
    zielu.gittoolbox (500.0.13+213)
    mobi.hsz.idea.gitignore (4.5.1)
    cn.yiiguxing.plugin.translate (3.5.1)
    izhangzhihao.rainbow.brackets.lite (1.0.1)
